# Generated by Django 6.0.3 on 2026-04-06 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_dimensionvariante_preciovariante_varianteservicio_and_more'),
        ('customers', '0008_remove_customer_codigo_branch_codigo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='BORRADOR', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CotizDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('instrumento_desc', models.CharField(max_length=255)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('serie', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='sales.cotizacion')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.varianteservicio')),
            ],
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['numero'], name='sales_cotiz_numero_d1ee91_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['fecha'], name='sales_cotiz_fecha_c55878_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizdetalle',
            index=models.Index(fields=['cotizacion'], name='sales_cotiz_cotizac_49d080_idx'),
        ),
    ]
