# Generated by Django 6.0.3 on 2026-04-09 17:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0013_customer_es_aliado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_empresa', models.CharField(blank=True, help_text='Código técnico que usa la empresa (ej: SIMET-2024-001, COT-001, etc.)', max_length=50, null=True, unique=True, verbose_name='Código Interno')),
                ('numero', models.CharField(blank=True, help_text='Número amigable para mostrar al cliente', max_length=50, unique=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='BORRADOR', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('certificate_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='customers.customer')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.branch')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(blank=True, max_length=100)),
                ('configuracion', models.JSONField(blank=True, default=dict, help_text='Configuración específica: puntos_temp, puntos_humedad, rango_masa, etc.')),
                ('cantidad', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('serie', models.CharField(blank=True, max_length=100)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales, comentarios, referencia a fotos')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.cotizacion')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.servicios', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Item de Cotización',
                'verbose_name_plural': 'Items de Cotizaciones',
            },
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['numero'], name='sales_cotiz_numero_d1ee91_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['fecha'], name='sales_cotiz_fecha_c55878_idx'),
        ),
        migrations.AddIndex(
            model_name='items',
            index=models.Index(fields=['cotizacion'], name='sales_items_cotizac_2f67cc_idx'),
        ),
        migrations.AddIndex(
            model_name='items',
            index=models.Index(fields=['servicio'], name='sales_items_servici_779f4a_idx'),
        ),
    ]
