# Generated by Django 6.0.3 on 2026-04-08 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_customer_identificacion_valida_customer_validado_sri'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='sucursal',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to='customers.branch'),
            preserve_default=False,
        ),
    ]
