# Generated by Django 6.0.3 on 2026-04-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_grupocotizacion_alter_items_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='archivo_pdf',
            field=models.FileField(blank=True, help_text='PDF generado de la cotización guardado en Supabase', null=True, upload_to='cotizaciones/pdfs/'),
        ),
    ]
