# Generated by Django 6.0.3 on 2026-04-08 16:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_varianteservicio_catalog_var_cod_var_f60782_idx_and_more'),
        ('customers', '0011_customer_identificacion_valida_customer_validado_sri'),
        ('sales', '0003_alter_cotizacion_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuracion', models.JSONField(blank=True, default=dict, help_text='Configuración específica: puntos_temp, puntos_humedad, rango_masa, etc.')),
                ('cantidad', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('instrumento_desc', models.CharField(max_length=255, verbose_name='Instrumento')),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('serie', models.CharField(blank=True, max_length=100)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales, comentarios, referencia a fotos')),
            ],
            options={
                'verbose_name': 'Detalle de Cotización',
                'verbose_name_plural': 'Detalles de Cotizaciones',
            },
        ),
        migrations.RemoveIndex(
            model_name='cotizdetalle',
            name='sales_cotiz_cotizac_49d080_idx',
        ),
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'verbose_name': 'Cotización', 'verbose_name_plural': 'Cotizaciones'},
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='sucursal',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='customers.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotizaciondetalle',
            name='cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='sales.cotizacion'),
        ),
        migrations.AddField(
            model_name='cotizaciondetalle',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.catalogoservicio', verbose_name='Servicio'),
        ),
        migrations.RemoveField(
            model_name='cotizdetalle',
            name='cotizacion',
        ),
        migrations.RemoveField(
            model_name='cotizdetalle',
            name='variante',
        ),
        migrations.AddIndex(
            model_name='cotizaciondetalle',
            index=models.Index(fields=['cotizacion'], name='sales_cotiz_cotizac_bd8e95_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizaciondetalle',
            index=models.Index(fields=['servicio'], name='sales_cotiz_servici_b56410_idx'),
        ),
        migrations.DeleteModel(
            name='CotizDetalle',
        ),
    ]
