# Generated by Django 6.0.3 on 2026-04-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_magnitude_base_price_and_more'),
        ('sales', '0003_cotizacion_archivo_pdf'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='items',
            name='sales_items_cotizac_2f67cc_idx',
        ),
        migrations.AddIndex(
            model_name='items',
            index=models.Index(fields=['grupo'], name='sales_items_grupo_i_3173ca_idx'),
        ),
        migrations.RemoveField(
            model_name='items',
            name='cotizacion',
        ),
    ]
