# Generated by Django 6.0.3 on 2026-04-08 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_varianteservicio_catalog_var_cod_var_f60782_idx_and_more'),
        ('sales', '0004_cotizaciondetalle_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CotizacionDetalle',
            new_name='CotizacionItems',
        ),
        migrations.RenameIndex(
            model_name='cotizacionitems',
            new_name='sales_cotiz_cotizac_80b265_idx',
            old_name='sales_cotiz_cotizac_bd8e95_idx',
        ),
        migrations.RenameIndex(
            model_name='cotizacionitems',
            new_name='sales_cotiz_servici_99dbe2_idx',
            old_name='sales_cotiz_servici_b56410_idx',
        ),
    ]
