# Generated by Django 6.0.3 on 2026-04-16 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_items_sales_items_cotizac_2f67cc_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.grupocotizacion'),
        ),
    ]
