# Generated by Django 6.0.3 on 2026-04-08 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_rename_cotizaciondetalle_cotizacionitems_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacionitems',
            options={'verbose_name': 'Item de Cotización', 'verbose_name_plural': 'Items de Cotizaciones'},
        ),
        migrations.RemoveField(
            model_name='cotizacionitems',
            name='instrumento_desc',
        ),
        migrations.AlterField(
            model_name='cotizacionitems',
            name='cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.cotizacion'),
        ),
    ]
