# Generated by Django 6.0.3 on 2026-04-16 17:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_unidades_magnitudeprice_accredited_and_more'),
        ('sales', '0006_alter_cotizacion_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuracion', models.JSONField(blank=True, default=dict)),
                ('cantidad', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('serie', models.CharField(blank=True, max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subitems', to='sales.items')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.servicios')),
            ],
            options={
                'verbose_name': 'SubItem de Cotización',
                'verbose_name_plural': 'SubItems de Cotizaciones',
                'indexes': [models.Index(fields=['item'], name='sales_subit_item_id_a2db2c_idx'), models.Index(fields=['servicio'], name='sales_subit_servici_0b9072_idx')],
            },
        ),
    ]
