# Generated by Django 6.0.3 on 2026-04-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_cotizacionitems_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='codigo_empresa',
            field=models.CharField(blank=True, help_text='Código técnico que usa la empresa (ej: SIMET-2024-001, COT-001, etc.)', max_length=50, null=True, unique=True, verbose_name='Código Interno'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='numero',
            field=models.CharField(blank=True, help_text='Número amigable para mostrar al cliente', max_length=50, unique=True),
        ),
    ]
