# Generated by Django 6.0.3 on 2026-04-17 13:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_customer_es_aliado'),
        ('sales', '0007_subitem'),
        ('work_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cotizacion',
            new_name='Quote',
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'verbose_name': 'Quote', 'verbose_name_plural': 'Quotes'},
        ),
        migrations.RenameIndex(
            model_name='quote',
            new_name='sales_quote_numero_892932_idx',
            old_name='sales_cotiz_numero_d1ee91_idx',
        ),
        migrations.RenameIndex(
            model_name='quote',
            new_name='sales_quote_fecha_84818c_idx',
            old_name='sales_cotiz_fecha_c55878_idx',
        ),
    ]
