# Generated by Django 6.0.3 on 2026-04-17 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_servicios_options'),
        ('sales', '0008_rename_cotizacion_quote_alter_quote_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GrupoCotizacion',
            new_name='QuoteGroup',
        ),
    ]
