# Generated by Django 6.0.3 on 2026-04-17 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_servicios_options'),
        ('sales', '0009_quotegroup_remove_grupocotizacion_cotizacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotegroup',
            options={'ordering': ['order']},
        ),
        migrations.RemoveIndex(
            model_name='items',
            name='sales_items_grupo_i_3173ca_idx',
        ),
        migrations.RenameField(
            model_name='quotegroup',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='quotegroup',
            old_name='orden',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='quotegroup',
            name='cotizacion',
        ),
        migrations.AddField(
            model_name='items',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.quotegroup'),
        ),
        migrations.AddField(
            model_name='quotegroup',
            name='quote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='sales.quote'),
        ),
        migrations.AddIndex(
            model_name='items',
            index=models.Index(fields=['group'], name='sales_items_group_i_d84855_idx'),
        ),
        migrations.RemoveField(
            model_name='items',
            name='grupo',
        ),
    ]
