# Generated by Django 6.0.3 on 2026-04-17 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_rename_instrumento_servicios_instrument_and_more'),
        ('customers', '0013_customer_es_aliado'),
        ('sales', '0010_alter_quotegroup_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'Item of Quote', 'verbose_name_plural': 'Items of Quotes'},
        ),
        migrations.RemoveIndex(
            model_name='items',
            name='sales_items_servici_779f4a_idx',
        ),
        migrations.RemoveIndex(
            model_name='quote',
            name='sales_quote_fecha_84818c_idx',
        ),
        migrations.RemoveIndex(
            model_name='subitem',
            name='sales_subit_servici_0b9072_idx',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='marca',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='configuracion',
            new_name='configuration',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='modelo',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='notas',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='cantidad',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='serie',
            new_name='serial',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='servicio',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='precio_unitario',
            new_name='unit_price',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='sucursal',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='cliente',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='fecha',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='observaciones',
            new_name='observations',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='vendedor',
            new_name='seller',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='estado',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='subitem',
            old_name='marca',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='subitem',
            old_name='configuracion',
            new_name='configuration',
        ),
        migrations.RenameField(
            model_name='subitem',
            old_name='modelo',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='subitem',
            old_name='notas',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='subitem',
            old_name='cantidad',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='subitem',
            old_name='serie',
            new_name='serial',
        ),
        migrations.RenameField(
            model_name='subitem',
            old_name='servicio',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='subitem',
            old_name='precio_unitario',
            new_name='unit_price',
        ),
        migrations.AlterField(
            model_name='quote',
            name='archivo_pdf',
            field=models.FileField(blank=True, help_text='PDF generado de la cotización guardado en Supabase', null=True, upload_to='quotes/pdfs/'),
        ),
        migrations.AddIndex(
            model_name='items',
            index=models.Index(fields=['service'], name='sales_items_service_5e11b2_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['date'], name='sales_quote_date_252ab3_idx'),
        ),
        migrations.AddIndex(
            model_name='subitem',
            index=models.Index(fields=['service'], name='sales_subit_service_09ffe3_idx'),
        ),
    ]
