# Generated by Django 6.0.3 on 2026-04-17 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_rename_servicios_services_and_more'),
        ('sales', '0011_alter_items_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.servicios', verbose_name='service'),
        ),
    ]
