# Generated by Django 6.0.3 on 2026-04-17 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_rename_nombre_magnitude_name'),
        ('sales', '0012_alter_items_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.services', verbose_name='service'),
        ),
    ]
