# Generated by Django 6.0.3 on 2026-04-20 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_customer_es_aliado'),
        ('sales', '0013_alter_items_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.branch', verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
    ]
