# Generated by Django 6.0.3 on 2026-04-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_alter_quote_branch_alter_quote_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='is_outsourced',
            field=models.BooleanField(default=False, verbose_name='¿Subcontratado?'),
        ),
    ]
