# Generated by Django 6.0.3 on 2026-04-20 18:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_alter_typeservice_table'),
        ('sales', '0015_items_is_outsourced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='items',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.quotegroup', verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='items',
            name='model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='items',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas adicionales, comentarios, referencia a fotos', verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='items',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='items',
            name='serial',
            field=models.CharField(blank=True, max_length=100, verbose_name='Serie'),
        ),
        migrations.AlterField(
            model_name='items',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.services', verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='items',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario'),
        ),
    ]
