# Generated by Django 6.0.3 on 2026-04-20 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_alter_provider_provider_type'),
        ('sales', '0016_alter_items_brand_alter_items_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='external_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='providers.provider', verbose_name='Enviar a (Lab Externo)'),
        ),
    ]
