# Generated by Django 6.0.3 on 2026-04-20 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_alter_typeservice_table'),
        ('sales', '0017_items_external_provider'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subitem',
            name='sales_subit_service_09ffe3_idx',
        ),
        migrations.AddField(
            model_name='subitem',
            name='magnitude_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.magnitudeprice', verbose_name='Precio de Magnitud'),
        ),
        migrations.AlterField(
            model_name='subitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por Punto'),
        ),
        migrations.AddIndex(
            model_name='subitem',
            index=models.Index(fields=['magnitude_price'], name='sales_subit_magnitu_bee146_idx'),
        ),
        migrations.RemoveField(
            model_name='subitem',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='subitem',
            name='configuration',
        ),
        migrations.RemoveField(
            model_name='subitem',
            name='model',
        ),
        migrations.RemoveField(
            model_name='subitem',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='subitem',
            name='serial',
        ),
        migrations.RemoveField(
            model_name='subitem',
            name='service',
        ),
    ]
