# Generated by Django 6.0.3 on 2026-04-20 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_remove_subitem_sales_subit_service_09ffe3_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='items',
            name='configuration',
        ),
        migrations.RemoveField(
            model_name='items',
            name='model',
        ),
        migrations.RemoveField(
            model_name='items',
            name='serial',
        ),
    ]
