# Generated by Django 6.0.3 on 2026-04-20 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_remove_items_brand_remove_items_configuration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='subitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad'),
        ),
    ]
