# Generated by Django 6.0.3 on 2026-04-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_alter_items_unit_price_alter_subitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='is_accredited',
            field=models.BooleanField(default=False, verbose_name='¿Acreditado?'),
        ),
        migrations.AddField(
            model_name='subitem',
            name='tag_snapshot',
            field=models.CharField(blank=True, help_text='Tag snapshot del precio de magnitud', max_length=50, verbose_name='Tag Snapshot'),
        ),
        migrations.AddField(
            model_name='subitem',
            name='technical_description',
            field=models.TextField(blank=True, help_text='Descripción técnica del subitem', verbose_name='Descripción Técnica'),
        ),
    ]
