# Generated by Django 6.0.3 on 2026-04-20 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_items_is_accredited_subitem_tag_snapshot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subitem',
            name='tag_snapshot',
        ),
    ]
