# Generated by Django 6.0.3 on 2026-04-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_remove_subitem_tag_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio por Punto'),
        ),
    ]
