# Generated by Django 6.0.3 on 2026-04-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_alter_subitem_unit_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotegroup',
            options={'verbose_name': 'Grupo de Cotización', 'verbose_name_plural': 'Grupos de Cotizaciones'},
        ),
        migrations.AddIndex(
            model_name='quotegroup',
            index=models.Index(fields=['quote'], name='sales_quote_quote_i_799e8a_idx'),
        ),
        migrations.AddIndex(
            model_name='quotegroup',
            index=models.Index(fields=['name'], name='sales_quote_name_b3d92c_idx'),
        ),
        migrations.AlterModelTable(
            name='quotegroup',
            table='sales_quote_group',
        ),
    ]
