# Generated by Django 6.0.3 on 2026-04-29 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_alter_asset_customer'),
        ('sales', '0024_alter_quotegroup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subitem',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.asset', verbose_name='Instrumento'),
        ),
    ]
