# Generated by Django 6.0.3 on 2026-04-29 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_subitem_asset'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subitem',
            name='sales_subit_magnitu_bee146_idx',
        ),
        migrations.RemoveField(
            model_name='subitem',
            name='magnitude_price',
        ),
    ]
