# Generated by Django 6.0.3 on 2026-04-29 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_alter_asset_customer'),
        ('catalog', '0030_rename_instruments_typeinstruments_and_more'),
        ('sales', '0026_remove_subitem_sales_subit_magnitu_bee146_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'Item del grupo', 'verbose_name_plural': 'Items de grupos'},
        ),
        migrations.AlterModelOptions(
            name='subitem',
            options={'verbose_name': 'SubItem', 'verbose_name_plural': 'SubItems'},
        ),
        migrations.AddField(
            model_name='subitem',
            name='magnitude_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.magnitudeprice', verbose_name='Tarifa de Magnitud'),
        ),
        migrations.AddIndex(
            model_name='subitem',
            index=models.Index(fields=['asset'], name='sales_subit_asset_i_231fe1_idx'),
        ),
        migrations.AddIndex(
            model_name='subitem',
            index=models.Index(fields=['magnitude_price'], name='sales_subit_magnitu_bee146_idx'),
        ),
    ]
