# Generated by Django 6.0.3 on 2026-04-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_alter_items_options_alter_subitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio unitario'),
        ),
    ]
