# Generated by Django 6.0.3 on 2026-04-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0028_alter_subitem_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Precio Unitario'),
        ),
    ]
