# Generated by Django 6.0.3 on 2026-04-01 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='ruc',
            new_name='ruc_cc',
        ),
    ]
