# Generated by Django 6.0.3 on 2026-04-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_ruc_customer_ruc_cc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='razon_social',
            new_name='apellido',
        ),
        migrations.AddField(
            model_name='customer',
            name='nombre',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
