# Generated by Django 6.0.3 on 2026-04-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_rename_razon_social_customer_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='direccion_matriz',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='es_activo',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='ruc_cc',
        ),
        migrations.AddField(
            model_name='customer',
            name='identificacion',
            field=models.CharField(default='', help_text='Ingrese RUC, Cédula o Pasaporte', max_length=13, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='nombre_completo',
            field=models.CharField(default='', max_length=255, verbose_name='Nombre Completo / Razón Social'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='tipo_identificacion',
            field=models.CharField(choices=[('RUC', 'RUC'), ('CED', 'Cédula'), ('PAS', 'Pasaporte')], default='RUC', max_length=3),
        ),
        migrations.AddField(
            model_name='customer',
            name='tipo_persona',
            field=models.CharField(choices=[('NAT', 'Persona Natural'), ('JUR', 'Persona Jurídica')], default='JUR', max_length=3),
        ),
    ]
