# Generated by Django 6.0.3 on 2026-04-01 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_customer_apellido_remove_customer_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='tipo_persona',
            new_name='tipo_cliente',
        ),
    ]
