# Generated by Django 6.0.3 on 2026-04-01 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_rename_tipo_persona_customer_tipo_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='tipo_cliente',
            new_name='tipo_persona',
        ),
    ]
