# Generated by Django 6.0.3 on 2026-04-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_rename_tipo_cliente_customer_tipo_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='codigo',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
    ]
