# Generated by Django 6.0.3 on 2026-04-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='codigo',
        ),
        migrations.AddField(
            model_name='branch',
            name='codigo',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
    ]
