# Generated by Django 6.0.3 on 2026-04-07 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_customer_created_at_customer_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='vendedor',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'VENDEDOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor asignado'),
        ),
    ]
