# Generated by Django 6.0.3 on 2026-04-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_alter_customer_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='identificacion_valida',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='validado_sri',
            field=models.BooleanField(default=False),
        ),
    ]
