# Generated by Django 6.0.3 on 2026-04-09 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_customer_identificacion_valida_customer_validado_sri'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='vendedor',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Vendedor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor asignado'),
        ),
    ]
