# Generated by Django 6.0.3 on 2026-04-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_alter_customer_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='es_aliado',
            field=models.BooleanField(default=False),
        ),
    ]
