# Generated by Django 6.0.3 on 2026-04-28 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('customers', '0014_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='model',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='equipment',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='internal_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Código interno'),
        ),
    ]
