# Generated by Django 6.0.3 on 2026-04-16 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_magnitude_alter_dimensionvariante_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentos',
            name='magnitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.magnitude'),
        ),
    ]
