"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

from datetime import timedelta


load_dotenv()

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ixdwh9caa*#!s_^t7%=-_b@n6)k&@4#sd@oam7i9!_$b$kivsl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'apps.users',      # Tu app de usuarios
    'apps.customers',
    'apps.catalog',
    'apps.sales',
    # 'apps.uploads',
    'drf_spectacular',
    'apps.work_orders',
    'storages',


]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL'),
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

AUTH_USER_MODEL = 'users.User'

# settings.py

# Datos del Laboratorio para PDFs
LAB_NOMBRE = "LABORATORIO DE CALIBRACIÓN S.A.C."
LAB_RUC = "20123456789"
LAB_DIRECCION = "Av. Principal 123, Lima - Perú"
LAB_TELEFONO = "(01) 123-4567"
LAB_EMAIL = "contacto@labcalibracion.com"

# URL del logo (opcional, puedes agregarlo al HTML)
LAB_LOGO_URL = "https://tudominio.com/static/img/logo_lab.png"

# Usar TUS nombres de variables del .env
SUPABASE_URL = os.getenv('SUPABASE_URL', 'http://192.168.10.15:8000')
# ← Service role para operaciones admin
SUPABASE_KEY = os.getenv('SUPABASE_SERVICE_ROLE_KEY')
# ← Anon key para operaciones públicas
SUPABASE_ANON_KEY = os.getenv('SUPABASE_KEY')
# ============================================
# CONFIGURACIÓN SUPABASE STORAGE vía S3 (django-storages)
# ============================================

# Credenciales S3 desde tu .env
AWS_ACCESS_KEY_ID = os.getenv('S3_PROTOCOL_ACCESS_KEY_ID', '625729a08b95bf1b7ff351a663f3a23c')
AWS_SECRET_ACCESS_KEY = os.getenv('S3_PROTOCOL_ACCESS_KEY_SECRET', '850181e4652dd023b7a98c58ae0d2d34bd487ee0cc3254aed6eda37307425907')
AWS_STORAGE_BUCKET_NAME = 'test-public'
AWS_S3_ENDPOINT_URL = f"{SUPABASE_URL}/storage/v1/s3"
AWS_S3_REGION_NAME = 'stub'
AWS_S3_CUSTOM_DOMAIN = f"{SUPABASE_URL}/storage/v1/s3/public/{AWS_STORAGE_BUCKET_NAME}"
AWS_DEFAULT_ACL = 'public-read'
AWS_S3_FILE_OVERWRITE = False
AWS_QUERYSTRING_AUTH = False  # URLs públicas sin token
AWS_S3_USE_SSL = False
AWS_S3_VERIFY = False
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_S3_ADDRESSING_STYLE = 'path'

# Configurar storages (Django 4.2+)
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Compatibilidad con versiones anteriores
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# URL base para archivos de medios
MEDIA_URL = f"{AWS_S3_CUSTOM_DOMAIN}/"
# ============ CONFIGURACIÓN CORS COMPLETA ============
# Permite tu frontend desde cualquier máquina en la red local
# ============ CONFIGURACIÓN FINAL (desarrollo) ============

# Hosts permitidos - modo desarrollo
ALLOWED_HOSTS = ['*']  # SOLO para desarrollo en red local

# CORS - modo desarrollo
CORS_ALLOW_ALL_ORIGINS = True  # Permite cualquier origen (fácil para pruebas)
CORS_ALLOW_CREDENTIALS = True

# Si quieres ser más específico (recomendado para producción después)
# CORS_ALLOWED_ORIGINS = [
#     "http://192.168.56.1:3000",
#     "http://localhost:3000",
# ]