# Generated by Django 6.0.3 on 2026-04-09 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usuariorol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rol',
        ),
        migrations.DeleteModel(
            name='UsuarioRol',
        ),
    ]
