# Generated by Django 6.0.3 on 2026-04-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Razón Social')),
                ('tax_id', models.CharField(max_length=20, unique=True, verbose_name='RUC/NIT')),
                ('provider_type', models.CharField(choices=[('LABORATORY', 'Laboratorio de Metrología'), ('MAINTENANCE', 'Mantenimiento/Reparación'), ('LOGISTICS', 'Transporte/Logística')], default='LABORATORY', max_length=20)),
                ('is_approved', models.BooleanField(default=False, verbose_name='Proveedor Homologado/Aprobado')),
                ('accreditation_file', models.FileField(blank=True, null=True, upload_to='providers/accreditations/', verbose_name='Certificado de Acreditación')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Vencimiento de Acreditación')),
            ],
        ),
    ]
