# Generated by Django 6.0.3 on 2026-04-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='tax_id',
            new_name='identification',
        ),
        migrations.AddField(
            model_name='provider',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='provider',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
    ]
