# Generated by Django 6.0.3 on 2026-04-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_rename_tax_id_provider_identification_provider_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='provider_type',
            field=models.CharField(choices=[('LABORATORY', 'Laboratorio de Metrología'), ('MAINTENANCE', 'Mantenimiento/Reparación'), ('LOGISTICS', 'Transporte/Logística')], default='LABORATORY', max_length=20, verbose_name='Tipo de Proveedor'),
        ),
    ]
