# Generated by Django 6.0.3 on 2026-04-28 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('catalog', '0030_rename_instruments_typeinstruments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='instrument_type',
        ),
        migrations.AddField(
            model_name='asset',
            name='type_instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_instrument_assets', to='catalog.typeinstruments'),
        ),
    ]
