# Generated by Django 6.0.3 on 2026-04-28 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_remove_asset_description_remove_asset_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='owner_customer',
        ),
    ]
