# Generated by Django 6.0.3 on 2026-04-28 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_remove_asset_owner_customer'),
        ('catalog', '0030_rename_instruments_typeinstruments_and_more'),
        ('customers', '0015_remove_equipment_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='customers.customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='owner_type',
            field=models.CharField(choices=[('customer', 'Cliente'), ('laboratory', 'Laboratorio')], default='customer', max_length=20, verbose_name='Tipo de Propietario'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type_instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_instrument_assets', to='catalog.typeinstruments', verbose_name='Tipo de Instrumento'),
        ),
    ]
