# Generated by Django 6.0.3 on 2026-04-28 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_alter_asset_name'),
        ('customers', '0015_remove_equipment_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='customers.customer', verbose_name='Cliente'),
        ),
    ]
