# Generated by Django 6.0.3 on 2026-04-20 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0013_alter_items_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Proceso'), ('PARTIAL', 'Parcial'), ('COMPLETED', 'Finalizada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Inicio')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Fin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='sales.quote', verbose_name='Cotización')),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='operations.workorder', verbose_name='Reemplaza a')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
                'db_table': 'operations_work_orders',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255, verbose_name='Nombre del Servicio')),
                ('configuration', models.JSONField(blank=True, default=dict, verbose_name='Configuración Técnica')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Cantidad')),
                ('notes', models.TextField(blank=True, verbose_name='Notas/Observaciones')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operations.workorder', verbose_name='Orden de Trabajo')),
            ],
            options={
                'verbose_name': 'Ítem de Orden',
                'verbose_name_plural': 'Ítems de Orden',
                'db_table': 'operations_work_order_items',
            },
        ),
    ]
