# Generated by Django 6.0.3 on 2026-04-20 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='actual_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin Real'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='actual_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio Real'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Asignado'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='is_onsite',
            field=models.BooleanField(default=False, verbose_name='¿Es en sitio?'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='location_address',
            field=models.TextField(blank=True, verbose_name='Dirección de ejecución'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Baja'), ('NORMAL', 'Normal'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], default='NORMAL', max_length=10, verbose_name='Prioridad'),
        ),
    ]
