# Generated by Django 6.0.3 on 2026-04-22 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_workorder_actual_end_workorder_actual_start_and_more'),
        ('providers', '0003_alter_provider_provider_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutsourcingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('expected_return_date', models.DateField(blank=True, null=True, verbose_name='Fecha estimada de retorno')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Guía de envío')),
                ('status', models.CharField(choices=[('SENT', 'Enviado'), ('RECEIVED', 'Recibido'), ('COMPLETED', 'Validado')], default='SENT', max_length=20)),
                ('service_request_pdf', models.FileField(blank=True, null=True, upload_to='requests/pdfs/')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='providers.provider')),
                ('work_order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outsourcing_request', to='operations.workorderitem')),
            ],
        ),
    ]
