# Generated by Django 6.0.3 on 2026-04-01 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magnitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Magnitud',
                'verbose_name_plural': 'Magnitudes',
            },
        ),
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Servicio',
                'verbose_name_plural': 'Tipos de Servicio',
            },
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo_base', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('magnitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.magnitud')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_facturacion', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('acreditado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.instrumento')),
                ('magnitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.magnitud')),
                ('procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.procedimiento')),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.tiposervicio')),
            ],
        ),
        migrations.CreateModel(
            name='VarianteServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_variante', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField()),
                ('acreditado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='catalog.catalogoservicio')),
            ],
        ),
        migrations.CreateModel(
            name='VarianteProc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.procedimiento')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.varianteservicio')),
            ],
        ),
        migrations.CreateModel(
            name='ParametroVariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_param', models.CharField(max_length=255)),
                ('valor', models.CharField(max_length=255)),
                ('unidad', models.CharField(max_length=50)),
                ('tipo_dato', models.CharField(max_length=50)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='catalog.varianteservicio')),
            ],
        ),
    ]
