# Generated by Django 6.0.3 on 2026-04-09 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magnitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instrumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo_base', models.CharField(blank=True, max_length=50)),
                ('magnitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.magnitud')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_facturacion', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('acreditado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.instrumentos')),
                ('magnitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.magnitud')),
                ('procedimiento_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.procedimiento')),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.tiposervicio')),
            ],
        ),
        migrations.CreateModel(
            name='VarianteServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_variante', models.CharField(blank=True, max_length=120)),
                ('descripcion', models.TextField()),
                ('acreditado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('procedimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.procedimiento')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='catalog.servicios')),
            ],
        ),
        migrations.CreateModel(
            name='PrecioVariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='catalog.varianteservicio')),
            ],
            options={
                'ordering': ['-vigente_desde'],
            },
        ),
        migrations.CreateModel(
            name='DimensionVariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dimension', models.CharField(max_length=30)),
                ('valor_entero', models.IntegerField(blank=True, null=True)),
                ('valor_texto', models.CharField(blank=True, max_length=100)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensiones', to='catalog.varianteservicio')),
            ],
        ),
        migrations.AddIndex(
            model_name='servicios',
            index=models.Index(fields=['cod_facturacion'], name='catalog_ser_cod_fac_0bab01_idx'),
        ),
        migrations.AddIndex(
            model_name='varianteservicio',
            index=models.Index(fields=['servicio'], name='catalog_var_servici_b89db3_idx'),
        ),
        migrations.AddIndex(
            model_name='preciovariante',
            index=models.Index(fields=['vigente_desde'], name='catalog_pre_vigente_26bdf3_idx'),
        ),
        migrations.AddIndex(
            model_name='dimensionvariante',
            index=models.Index(fields=['tipo_dimension'], name='catalog_dim_tipo_di_b3b73b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dimensionvariante',
            unique_together={('variante', 'tipo_dimension')},
        ),
    ]
