# Generated by Django 6.0.3 on 2026-04-02 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varianteproc',
            name='procedimiento',
        ),
        migrations.RemoveField(
            model_name='varianteproc',
            name='variante',
        ),
        migrations.RemoveField(
            model_name='varianteservicio',
            name='servicio',
        ),
        migrations.AlterModelOptions(
            name='magnitud',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tiposervicio',
            options={},
        ),
        migrations.RenameField(
            model_name='magnitud',
            old_name='estado',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='tiposervicio',
            old_name='estado',
            new_name='activo',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='catalogoservicio',
            name='patron',
            field=models.CharField(choices=[('FIJO', 'Fijo'), ('PUNTOS', 'Puntos'), ('RANGO', 'Rango'), ('COMB', 'Combinado')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogoservicio',
            name='precio_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='catalogoservicio',
            name='precio_base_no_acreditado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='catalogoservicio',
            name='cod_facturacion',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='catalogoservicio',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='catalogoservicio',
            name='procedimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.procedimiento'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='codigo_base',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='magnitud',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='TarifaPunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_eje', models.CharField(choices=[('TEMP', 'Temp'), ('HUM', 'Hum'), ('PH', 'Ph'), ('BRIX', 'Brix')], max_length=10)),
                ('num_punto', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acreditado', models.BooleanField(default=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.catalogoservicio')),
            ],
            options={
                'unique_together': {('servicio', 'tipo_eje', 'num_punto', 'acreditado')},
            },
        ),
        migrations.CreateModel(
            name='TarifaRango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_rango', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=150)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acreditado', models.BooleanField(default=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.catalogoservicio')),
            ],
            options={
                'unique_together': {('servicio', 'codigo_rango', 'acreditado')},
            },
        ),
        migrations.DeleteModel(
            name='ParametroVariante',
        ),
        migrations.DeleteModel(
            name='VarianteProc',
        ),
        migrations.DeleteModel(
            name='VarianteServicio',
        ),
    ]
