# Generated by Django 6.0.3 on 2026-04-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_varianteproc_procedimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogoservicio',
            name='nombre',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
