# Generated by Django 6.0.3 on 2026-04-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_servicios_precio_max_servicios_precio_min'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='servicios',
            name='catalog_ser_cod_fac_0bab01_idx',
        ),
        migrations.RenameField(
            model_name='servicios',
            old_name='cod_facturacion',
            new_name='code',
        ),
        migrations.AddIndex(
            model_name='servicios',
            index=models.Index(fields=['code'], name='catalog_ser_code_8de57a_idx'),
        ),
    ]
