# Generated by Django 6.0.3 on 2026-04-06 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_catalogoservicio_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimensionVariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dimension', models.CharField(max_length=30)),
                ('valor_entero', models.IntegerField(blank=True, null=True)),
                ('valor_texto', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PrecioVariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-vigente_desde'],
            },
        ),
        migrations.CreateModel(
            name='VarianteServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_variante', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField()),
                ('acreditado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tarifapunto',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tarifapunto',
            name='servicio',
        ),
        migrations.AlterUniqueTogether(
            name='tarifarango',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tarifarango',
            name='servicio',
        ),
        migrations.RenameField(
            model_name='catalogoservicio',
            old_name='procedimiento',
            new_name='procedimiento_base',
        ),
        migrations.RemoveField(
            model_name='catalogoservicio',
            name='patron',
        ),
        migrations.RemoveField(
            model_name='catalogoservicio',
            name='precio_base',
        ),
        migrations.RemoveField(
            model_name='catalogoservicio',
            name='precio_base_no_acreditado',
        ),
        migrations.AddIndex(
            model_name='catalogoservicio',
            index=models.Index(fields=['cod_facturacion'], name='catalog_cat_cod_fac_3905dc_idx'),
        ),
        migrations.AddField(
            model_name='varianteservicio',
            name='procedimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.procedimiento'),
        ),
        migrations.AddField(
            model_name='varianteservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='catalog.catalogoservicio'),
        ),
        migrations.AddField(
            model_name='preciovariante',
            name='variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='catalog.varianteservicio'),
        ),
        migrations.AddField(
            model_name='dimensionvariante',
            name='variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensiones', to='catalog.varianteservicio'),
        ),
        migrations.DeleteModel(
            name='TarifaPunto',
        ),
        migrations.DeleteModel(
            name='TarifaRango',
        ),
        migrations.AddIndex(
            model_name='varianteservicio',
            index=models.Index(fields=['servicio'], name='catalog_var_servici_b89db3_idx'),
        ),
        migrations.AddIndex(
            model_name='varianteservicio',
            index=models.Index(fields=['cod_variante'], name='catalog_var_cod_var_f60782_idx'),
        ),
        migrations.AddIndex(
            model_name='preciovariante',
            index=models.Index(fields=['vigente_desde'], name='catalog_pre_vigente_26bdf3_idx'),
        ),
        migrations.AddIndex(
            model_name='dimensionvariante',
            index=models.Index(fields=['tipo_dimension'], name='catalog_dim_tipo_di_b3b73b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dimensionvariante',
            unique_together={('variante', 'tipo_dimension')},
        ),
    ]
