# Generated by Django 6.0.3 on 2026-04-16 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_magnitude_alter_dimensionvariante_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dimensionvariante',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='dimensionvariante',
            name='catalog_dim_tipo_di_b3b73b_idx',
        ),
        migrations.RemoveIndex(
            model_name='preciovariante',
            name='catalog_pre_vigente_26bdf3_idx',
        ),
        migrations.RemoveIndex(
            model_name='varianteservicio',
            name='catalog_var_servici_b89db3_idx',
        ),
        migrations.AddField(
            model_name='magnitude',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='magnitude',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='magnitude',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='magnitude',
            name='range_max',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='magnitude',
            name='range_min',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='magnitude',
            name='tag',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instrumentos',
            name='magnitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.magnitude'),
        ),
        migrations.RemoveField(
            model_name='preciovariante',
            name='variante',
        ),
        migrations.RemoveField(
            model_name='varianteservicio',
            name='procedimiento',
        ),
        migrations.RemoveField(
            model_name='varianteservicio',
            name='servicio',
        ),
        migrations.DeleteModel(
            name='DimensionVariante',
        ),
        migrations.DeleteModel(
            name='PrecioVariante',
        ),
        migrations.DeleteModel(
            name='VarianteServicio',
        ),
    ]
