# Generated by Django 6.0.3 on 2026-04-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_dimensionvariante_preciovariante_varianteservicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varianteservicio',
            name='cod_variante',
            field=models.CharField(blank=True, max_length=120, unique=True),
        ),
    ]
