# Generated by Django 6.0.3 on 2026-04-16 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_dimensionvariante_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magnitude',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='magnitude',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='magnitude',
            name='min_price',
        ),
        migrations.RemoveField(
            model_name='magnitude',
            name='range_max',
        ),
        migrations.RemoveField(
            model_name='magnitude',
            name='range_min',
        ),
        migrations.RemoveField(
            model_name='magnitude',
            name='tag',
        ),
        migrations.CreateModel(
            name='MagnitudePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('range_min', models.CharField(max_length=100)),
                ('range_max', models.CharField(max_length=100)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('magnitude', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.magnitude')),
            ],
            options={
                'db_table': 'catalog_magnitude_price',
            },
        ),
    ]
