# Generated by Django 6.0.3 on 2026-04-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_varianteservicio_cod_variante'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='varianteservicio',
            name='catalog_var_cod_var_f60782_idx',
        ),
        migrations.AlterField(
            model_name='varianteservicio',
            name='cod_variante',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
