# Generated by Django 6.0.3 on 2026-04-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_magnitude_base_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('simbolo', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='magnitudeprice',
            name='accredited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='magnitudeprice',
            name='observation',
            field=models.TextField(blank=True),
        ),
    ]
