# Generated by Django 6.0.3 on 2026-04-16 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_unidades_magnitudeprice_accredited_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumentos',
            name='magnitud',
        ),
        migrations.CreateModel(
            name='CatalogInstrumentMagnitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=1)),
                ('obligatorio', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magnitudes', to='catalog.instrumentos')),
                ('magnitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.magnitude')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('instrumento', 'magnitud')},
            },
        ),
    ]
