# Generated by Django 6.0.3 on 2026-04-16 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_instrumentos_magnitud_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CatalogInstrumentMagnitudes',
            new_name='InstrumentMagnitudes',
        ),
        migrations.AlterModelTable(
            name='instrumentmagnitudes',
            table='catalog_instrument_magnitudes',
        ),
    ]
