# Generated by Django 6.0.3 on 2026-04-16 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_rename_cataloginstrumentmagnitudes_instrumentmagnitudes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios',
            name='magnitud',
        ),
    ]
