# Generated by Django 6.0.3 on 2026-04-16 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_servicios_magnitud'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instrumentos',
            new_name='Instruments',
        ),
    ]
