# Generated by Django 6.0.3 on 2026-04-16 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_rename_instrumentos_instruments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Procedimiento',
            new_name='Procedures',
        ),
        migrations.CreateModel(
            name='ProceduresMagnitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magnitude', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.magnitude')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.procedures')),
            ],
            options={
                'db_table': 'catalog_procedures_magnitudes',
                'ordering': ['procedure'],
                'unique_together': {('procedure', 'magnitude')},
            },
        ),
    ]
