# Generated by Django 6.0.3 on 2026-04-16 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_rename_procedimiento_procedures_proceduresmagnitudes'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruments',
            name='is_measurable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='instrumentmagnitudes',
            name='magnitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.magnitude'),
        ),
    ]
