# Generated by Django 6.0.3 on 2026-04-16 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_instruments_is_measurable_and_more'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='TypeService',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=100, unique=True)),
        #         ('behavior', models.CharField(choices=[('medible', 'Medible (con instrumento y magnitud)'), ('tiempo', 'Por tiempo (días/horas)'), ('gasto', 'Gasto real (viáticos)'), ('mixto', 'Mixto (puede ser ambos)')], default='medible', max_length=20)),
        #         ('requires_instrument', models.BooleanField(default=True)),
        #         ('requires_magnitude', models.BooleanField(default=True)),
        #         ('uses_range_prices', models.BooleanField(default=True)),
        #         ('active', models.BooleanField(default=True)),
        #     ],
        #     options={
        #         'verbose_name': 'Type of Service',
        #         'verbose_name_plural': 'Types of Services',
        #     },
        # )
        migrations.RenameModel(
            old_name='TipoServicio',
            new_name='TypeService',
        ),
        migrations.RenameField(
            model_name='magnitude',
            old_name='activo',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='precio_max',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='precio_min',
        ),
        migrations.AddField(
            model_name='procedures',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='instrumentmagnitudes',
            name='obligatorio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='tipo_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.typeservice'),
        ),
        # migrations.RenameModel(
        #     old_name='TipoServicio',
        #     new_name='TypeService',
        # ),
    ]
