# Generated by Django 6.0.3 on 2026-04-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_typeservice_rename_activo_magnitude_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeservice',
            options={'verbose_name': 'Type of Service', 'verbose_name_plural': 'Types of Services'},
        ),
        migrations.RenameField(
            model_name='typeservice',
            old_name='activo',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='typeservice',
            old_name='nombre',
            new_name='name',
        ),
        migrations.AddField(
            model_name='typeservice',
            name='behavior',
            field=models.CharField(choices=[('medible', 'Medible (con instrumento y magnitud)'), ('tiempo', 'Por tiempo (días/horas)'), ('gasto', 'Gasto real (viáticos)'), ('mixto', 'Mixto (puede ser ambos)')], default='medible', max_length=20),
        ),
        migrations.AddField(
            model_name='typeservice',
            name='requires_instrument',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='typeservice',
            name='requires_magnitude',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='typeservice',
            name='uses_range_prices',
            field=models.BooleanField(default=True),
        ),
    ]
