# Generated by Django 6.0.3 on 2026-04-16 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_typeservice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumentmagnitudes',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='instrumentmagnitudes',
            old_name='instrumento',
            new_name='instrument',
        ),
        migrations.RenameField(
            model_name='instrumentmagnitudes',
            old_name='magnitud',
            new_name='magnitude',
        ),
        migrations.RenameField(
            model_name='instrumentmagnitudes',
            old_name='obligatorio',
            new_name='obligatory',
        ),
        migrations.RenameField(
            model_name='instrumentmagnitudes',
            old_name='observaciones',
            new_name='observations',
        ),
        migrations.RenameField(
            model_name='instrumentmagnitudes',
            old_name='orden',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='instruments',
            old_name='codigo_base',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='instruments',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='procedures',
            old_name='codigo',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='procedures',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='servicios',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='acreditado',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='procedimiento_base',
        ),
        migrations.AlterUniqueTogether(
            name='instrumentmagnitudes',
            unique_together={('instrument', 'magnitude')},
        ),
    ]
