# Generated by Django 6.0.3 on 2026-04-16 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_instrumentmagnitudes_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicios',
            options={'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AddField(
            model_name='servicios',
            name='acreditado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicios',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicios',
            name='observaciones_internas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicios',
            name='precio_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicios',
            name='procedimiento_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.procedures'),
        ),
        migrations.AddIndex(
            model_name='servicios',
            index=models.Index(fields=['active'], name='catalog_ser_active_e0a2ab_idx'),
        ),
    ]
