# Generated by Django 6.0.3 on 2026-04-16 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_servicios_options_servicios_acreditado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios',
            name='procedimiento_base',
        ),
    ]
