# Generated by Django 6.0.3 on 2026-04-16 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_remove_servicios_procedimiento_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='instrumento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='catalog.instruments'),
        ),
    ]
