# Generated by Django 6.0.3 on 2026-04-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_servicios_instrumento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicios',
            options={'verbose_name': 'service', 'verbose_name_plural': 'services'},
        ),
    ]
