# Generated by Django 6.0.3 on 2026-04-17 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_servicios_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicios',
            old_name='instrumento',
            new_name='instrument',
        ),
        migrations.RenameField(
            model_name='servicios',
            old_name='tipo_servicio',
            new_name='type_service',
        ),
    ]
