# Generated by Django 6.0.3 on 2026-04-17 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_rename_instrumento_servicios_instrument_and_more'),
        ('sales', '0011_alter_items_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicios',
            new_name='Services',
        ),
        migrations.RenameIndex(
            model_name='services',
            new_name='catalog_ser_code_48619e_idx',
            old_name='catalog_ser_code_8de57a_idx',
        ),
        migrations.RenameIndex(
            model_name='services',
            new_name='catalog_ser_active_ec38b3_idx',
            old_name='catalog_ser_active_e0a2ab_idx',
        ),
    ]
