# Generated by Django 6.0.3 on 2026-04-17 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_rename_servicios_services_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='magnitude',
            old_name='nombre',
            new_name='name',
        ),
    ]
