# Generated by Django 6.0.3 on 2026-04-20 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_rename_nombre_magnitude_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='magnitude',
            name='unit',
            field=models.ManyToManyField(blank=True, null=True, related_name='magnitudes', to='catalog.unidades'),
        ),
        migrations.AddField(
            model_name='magnitudeprice',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.unidades'),
        ),
    ]
