# Generated by Django 6.0.3 on 2026-04-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_magnitude_unit_magnitudeprice_unit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Unidades',
            new_name='Units',
        ),
    ]
