# Generated by Django 6.0.3 on 2026-04-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_rename_unidades_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='units',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='units',
            old_name='simbolo',
            new_name='symbol',
        ),
    ]
