# Generated by Django 6.0.3 on 2026-04-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_rename_nombre_units_name_rename_simbolo_units_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='acreditado',
        ),
        migrations.AddField(
            model_name='instruments',
            name='alternative_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='magnitudeprice',
            name='range_max',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='magnitudeprice',
            name='range_min',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
