# Generated by Django 6.0.3 on 2026-04-20 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_remove_services_acreditado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instruments',
            options={'verbose_name': 'Instrument', 'verbose_name_plural': 'Instruments'},
        ),
        migrations.AlterModelOptions(
            name='magnitude',
            options={'verbose_name': 'Magnitude', 'verbose_name_plural': 'Magnitudes'},
        ),
        migrations.AlterModelOptions(
            name='magnitudeprice',
            options={'verbose_name': 'Magnitude Price', 'verbose_name_plural': 'Magnitude Prices'},
        ),
        migrations.AlterModelOptions(
            name='procedures',
            options={'verbose_name': 'Procedure', 'verbose_name_plural': 'Procedures'},
        ),
        migrations.AlterModelOptions(
            name='units',
            options={'verbose_name': 'Unit', 'verbose_name_plural': 'Units'},
        ),
    ]
