# Generated by Django 6.0.3 on 2026-04-20 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_alter_instruments_options_alter_magnitude_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='typeservice',
            table='catalog_type_service',
        ),
    ]
