# Generated by Django 6.0.3 on 2026-04-27 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_alter_typeservice_table'),
        ('customers', '0014_equipment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instruments',
            new_name='TypeInstruments',
        ),
        migrations.AlterModelOptions(
            name='typeinstruments',
            options={'verbose_name': 'Type of Instrument', 'verbose_name_plural': 'Types of Instruments'},
        ),
        migrations.AlterModelTable(
            name='typeinstruments',
            table='catalog_type_instruments',
        ),
    ]
